import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
//constants
// ──────────────────────────────────────────────────── 🟩 ─
import Sidebar from '@/components/Sidebar';

// ──────────────────────────────────────────────────── 🟩 ─

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-dot m-10  gap-4 font-opensans overflow-x-hidden ">
        <Sidebar />
        <div className=" mt-14 md:ml-[240px] md:mr-5 ml-20 flex flex-col  justify-center items-center  ">
          {children}
        </div>
      </body>
    </html>
  );
}
